apiVersion: apps/v1
kind: Deployment
  name: rtorrentvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtorrentvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rtorrentvpn
    spec:
      containers:
        - env:
            - name: DEBUG
              value: "false"
            - name: ENABLE_AUTODL_IRSSI
              value: "yes"
            - name: ENABLE_PRIVOXY
              value: "yes"
            - name: ENABLE_RPC2
              value: "yes"
            - name: ENABLE_RPC2_AUTH
              value: "yes"
            - name: ENABLE_WEBUI_AUTH
              value: "yes"
            - name: LAN_NETWORK
              value: 192.168.1.0/24
            - name: NAME_SERVERS
              value: 84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
            - name: PGID
              value: "0"
            - name: PHP_TZ
              value: UTC
            - name: PUID
              value: "0"
            - name: RPC2_PASS
              value: NzRhMjE4NjUzZDYw
            - name: RPC2_USER
              value: admin
            - name: STRICT_PORT_FORWARD
              value: "yes"
            - name: UMASK
              value: "000"
            - name: VPN_CLIENT
              value: openvpn
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_INPUT_PORTS
              value: "1234"
            - name: VPN_OUTPUT_PORTS
              value: "5678"
            - name: VPN_PASS
              value: mypassword
            - name: VPN_PROV
              value: pia
            - name: VPN_USER
              value: myusername
            - name: WEBUI_PASS
              value: NzRhMjE4NjUzZDYw
            - name: WEBUI_USER
              value: admin
          image: binhex/arch-rtorrentvpn
          name: rtorrentvpn
          ports:
            - containerPort: 9080
            - containerPort: 9443
            - containerPort: 8118
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: pvc-rtorrentvpn-downloads
            - mountPath: /config
              name: pvc-rtorrentvpn-config
      restartPolicy: Always
      volumes:
        - name: pvc-rtorrentvpn
          persistentVolumeClaim:
            claimName: pvc-rtorrentvpn-downloads
            readOnly: false
status: {}
