---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: torrent
  namespace: torrent 
  name: rtorrentvpn
spec:
  selector:
    matchLabels:
      app: torrent
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
        - image: romancin/rutorrent-flood:latest
          name: rtorrent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443   
              name: https-torrent
              protocol: TCP
            - containerPort: 3000   
              name: 3000-torrent
              protocol: TCP     
            - containerPort: 51415   
              name: 51415-torrent
              protocol: TCP                                                         
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: 8989
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          #   successThreshold: 1
          #   timeoutSeconds: 2
          # livenessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   tcpSocket:
          #     port: 8989
          #   timeoutSeconds: 1
          volumeMounts:
            - mountPath: /data
              name: torrent-downloads        
            - mountPath: /config
              name: torrent-config
          env:
           - name: DEBUG
             value: "false"          
           - name: TZ
             value: Europe/Oslo    
      volumes:
        - name: torrent-config
          persistentVolumeClaim:
            claimName: pvc-torrent-config
        - name: torrent-downloads
          persistentVolumeClaim:
            claimName: pvc-torrent-downloads                

         