---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rtorrentvpn
  name: rtorrentvpn
  namespace: downloads  
spec:
  selector:
    matchLabels:
      app: rtorrentvpn
  template:
    metadata:
      labels:
        app: rtorrentvpn
    spec:
      containers:
          image: binhex/arch-rtorrentvpn
          name: rtorrentvpn
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
              name: http-rtorrentvpn
              protocol: TCP
            - containerPort: 9443
              name: https-rtorrentvpn
              protocol: TCP    
            - containerPort: 8118
              name: vpn-rtorrentvpn
              protocol: TCP                           
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8989
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /data
              name: torrent-downloads        
            - mountPath: /config
              name: torrent-config
          env:
           - name: DEBUG
             value: "false"
           - name: ENABLE_AUTODL_IRSSI
             value: "yes"
           - name: ENABLE_PRIVOXY
             value: "yes"
           - name: ENABLE_RPC2
             value: "yes"
           - name: ENABLE_RPC2_AUTH
             value: "yes"
           - name: ENABLE_WEBUI_AUTH
             value: "yes"
           - name: LAN_NETWORK
             value: 192.168.1.0/24
           - name: NAME_SERVERS
             value: 84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
           - name: PGID
             value: "0"
           - name: PHP_TZ
             value: Europe/Oslo  
           - name: PUID
             value: "0"
           - name: RPC2_PASS
             value: NzRhMjE4NjUzZDYw
           - name: RPC2_USER
             value: admin
           - name: STRICT_PORT_FORWARD
             value: "yes"
           - name: UMASK
             value: "000"
           - name: VPN_CLIENT
             value: openvpn
           - name: VPN_ENABLED
             value: "yes"
           - name: VPN_INPUT_PORTS
             value: "1234"
           - name: VPN_OUTPUT_PORTS
             value: "5678"
           - name: VPN_PASS
             value: mypassword
           - name: VPN_PROV
             value: pia
           - name: VPN_USER
             value: myusername
           - name: WEBUI_PASS
             value: NzRhMjE4NjUzZDYw
           - name: WEBUI_USER
             value: admin          
           - name: TZ
             value: Europe/Oslo    
      volumes:
        - name: torrent-config
          persistentVolumeClaim:
            claimName: pvc-torrent-config
        - name: torrent-downloads
          persistentVolumeClaim:
            claimName: pvc-torrent-downloads                

         