---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: torrent
#   namespace: torrent 
#   name: rutorrent
# spec:
#   selector:
#     matchLabels:
#       app: torrent
#   template:
#     metadata:
#       labels:
#         app: torrent
#     spec:
#       containers:
#         - image: romancin/rutorrent-flood:latest
#           name: rutorrent
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 80   
#               name: http-torrent          
#             - containerPort: 443   
#               name: https-torrent
#               protocol: TCP
#             - containerPort: 3000   
#               name: flood-torrent
#               protocol: TCP     
#             - containerPort: 51415   
#               name: 51415-torrent
#               protocol: TCP                                                         
#           readinessProbe:
#             failureThreshold: 3
#             httpGet:
#               path: /
#               port: 80
#               scheme: HTTP
#             initialDelaySeconds: 10
#             periodSeconds: 30
#             successThreshold: 1
#             timeoutSeconds: 2
#           livenessProbe:
#             failureThreshold: 3
#             initialDelaySeconds: 30
#             periodSeconds: 10
#             successThreshold: 1
#             tcpSocket:
#               port: 80
#             timeoutSeconds: 1
#           volumeMounts:
#             - mountPath: /data
#               name: torrent-downloads        
#             - mountPath: /config
#               name: torrent-config
#           env:
#            - name: PGID
#              value: "0"
#            - name: PUID
#              value: "0"
#            - name: TZ
#              value: Europe/Oslo  
#       volumes:
#         - name: torrent-config
#           persistentVolumeClaim:
#             claimName: pvc-torrent-config
#         - name: torrent-downloads
#           persistentVolumeClaim:
#             claimName: pvc-torrent-downloads                

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: torrent
  namespace: torrent 
  name: deluge
spec:
  selector:
    matchLabels:
      app: torrent
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
        - image: linuxserver/deluge:amd64-latest
          name: deluge
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8112 
              name: http-torrent 
            - containerPort: 6881   
              name: torrent-tcp
              protocol: TCP 
            - containerPort: 6881   
              name: torrent-udp
              protocol: UDP                                                      
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8112
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8112
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /downloads
              name: torrent-downloads        
            - mountPath: /config
              name: torrent-config
          env:       
           - name: TZ
             value: Europe/Oslo  
           - name: PUID
             value: "0"
           - name: PGID
             value: "0"               
      volumes:
        - name: torrent-config
          persistentVolumeClaim:
            claimName: pvc-torrent-config
        - name: torrent-downloads
          persistentVolumeClaim:
            claimName: pvc-torrent-downloads         
         