apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: torrent
  namespace: torrent 
  name: pv-nfs-torrent-downloads
spec:
  capacity:
    storage: 1600Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: madara.home
    path: "/volume1/share/downloads"
  mountOptions:
    - nfsvers=4.1
---   
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   labels:
#     app: torrent
#   namespace: torrent 
#   name: pv-nfs-torrent-config
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     server: madara.home
#     path: "/volume1/share/k8s-config"
#   mountOptions:
#     - nfsvers=4.1
# ---           