apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: torrent
  namespace: downloads
  name: pv-nfs-torrent-downloads
spec:
  capacity:
    storage: 1600Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/downloads"
  mountOptions:
    - nfsvers=4.1
---   
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: torrent
  namespace: downloads
  name: pv-nfs-torrent-config
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/k8s-config/torrent"
  mountOptions:
    - nfsvers=4.1
---           