apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rtorrentvpn-downloads
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rtorrentvpn-config
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}

