# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: torrent
#   name: pvc-torrent-config
#   namespace: downloads 
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 400Mi  
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: torrent
  namespace: downloads
  name: pvc-torrent-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-torrent-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: torrent
  namespace: downloads
  name: pvc-torrent-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 9Gi
  volumeName: pv-nfs-torrent-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: torrent
  namespace: downloads
  name: pvc-torrent-time
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---

