apiVersion: v1
kind: Service
metadata:
  labels:
    app: torrent
  namespace: torrent 
  name: svc-rutorrent
spec:
  ports:
    - name: "http"
      port: 3001
      protocol: TCP
      targetPort: http-torrent  
    - name: "https"
      port: 6881 
      protocol: TCP
      targetPort: torrent-port
  selector:
    app: torrent   
