apiVersion: v1
kind: Service
metadata:
  labels:
    app: torrent
  namespace: downloads
  name: svc-rutorrent
spec:
  ports:
    - name: "http"
      port: 9080
      targetPort: http-torrent 
    - name: "https"
      port: 9443 
      # protocol: TCP
      targetPort: https-torrent 
    - name: "torrent"
      port: 8118 
      # protocol: UDP
      targetPort: torrent

  selector:
    app: torrent   
