apiVersion: v1
kind: Service
metadata:
  labels:
    app: torrent
  namespace: torrent 
  name: svc-rutorrent
spec:
  ports:
    - name: "http"
      port: 3001
      protocol: TCP
      targetPort: http-torrent 
    - name: "scgi"
      port: 3001
      protocol: TCP
      targetPort: scgi-port
    - name: "torrent-tcp"
      port: 51413 
      protocol: TCP
      targetPort: torrent-tcp    
    - name: "torrent-udp"
      port: 6881 
      protocol: UDP
      targetPort: torrent-udp

  selector:
    app: torrent   
