apiVersion: v1
kind: Service
metadata:
  labels:
    app: torrent
  namespace: torrent 
  name: svc-rutorrent
spec:
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: http-torrent  
    - name: "https"
      port: 443
      protocol: TCP
      targetPort: https-torrent
    - name: "51415"
      port: 51415
      targetPort: 51415-torrent
    - name: "flood"
      port: 3000 
      targetPort: flood-torrent
  selector:
    app: torrent   
