apiVersion: v1
kind: Service
metadata:
  labels:
    app: torrent
  namespace: torrent 
  name: svc-rutorrent
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: http-torrent 
    - name: "torrent-tcp"
      port: 8000 
      protocol: TCP
      targetPort: XMLRPC-PORT    
    - name: "torrent-udp"
      port: 6881 
      protocol: UDP
      targetPort: RT-DHT-PORT

  selector:
    app: torrent   
