# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: homeassistant-pvc
#   namespace: automation  
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: homeassistant
  namespace: automation 
  name: homeassistant-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 30Gi
  volumeName: pv-nfs-homeassistant-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mqtt
  namespace: automation 
  name: mqtt-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-mqtt-config