apiVersion: v1
kind: Service
metadata:
  name: svc-homeassistant
  namespace: automation
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-homeassistant
  selector:
    app: homeassistant      

