apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  namespace: downloads  
  name: svc-sonarr
spec:
  ports:
    - port: 8989
      protocol: TCP
      targetPort: http-sonarr
  selector:
    app: sonarr      

