---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prowlarr
  name: prowlarr
  namespace: downloads  
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
              name: http-prowlarr
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 9696
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 50
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 9696
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
          env:
           - name: PGID
             value: "1000"
           - name: PUID
             value: "1000"
           - name: TZ
             value: Europe/Oslo    
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: pvc-prowlarr-config