apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-prowlarr-config
  namespace: downloads    
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/k8s-config/prowlarr"
  mountOptions:
    - nfsvers=4.1