# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: prowlarr
#   name: pvc-prowlarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prowlarr-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-prowlarr-config
---