apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prowlarr
  name: pvc-prowlarr-config
  namespace: downloads    
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 9Gi
  volumeName: pv-nfs-prowlarr-config      