---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  namespace: plex    
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker
          imagePullPolicy: IfNotPresent
          # resources:
          #   limits:
          #     nvidia.com/gpu: 1 # requesting 1 GPUs          
          ports:
            - containerPort: 32400
              name: http-plex
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /web/index.html#!/
              port: 32400
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 50
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 32400
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /data
              name: plex-data
            - mountPath: /transcode
              name: plex-transcode                            
          env:      
           - name: TZ
             value: Europe/Oslo    
           - name: PLEX_CLAIM
             value: claim-uV-sr7rpaspa7ypHCTLx                
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: pvc-plex-config
        - name: plex-transcode
          persistentVolumeClaim:
            claimName: pvc-plex-transcode
        - name: plex-data
          persistentVolumeClaim:
            claimName: pvc-plex-data                        