---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex

spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPUs          
          ports:
            - containerPort: 32400
              name: http-plex
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /web/index.html#!/
              port: 32400
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 50
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 32400
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /tv
              name: plex-tv
            - mountPath: /movies
              name: plex-movies                            
          env:
           - name: PGID
             value: "1000"
           - name: PUID
             value: "1000"
           - name: TZ
             value: Europe/Oslo    
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: pvc-plex-config
        - name: plex-tv
          persistentVolumeClaim:
            claimName: pvc-plex-tvshows
        - name: plex-movies
          persistentVolumeClaim:
            claimName: pvc-plex-movies                        