apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: plex
  namespace: plex
  name: plex-ingress
  annotations:
    #kubernetes.io/ingress.class: nginx  
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: plex.ting
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-plex
            port:
              number: 32400