apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  name: pvc-plex-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
