apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  namespace: media
  name: pvc-plex-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 14Gi
  volumeName: pv-nfs-plex-config      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  namespace: media
  name: pvc-plex-movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-plex-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  namespace: media
  name: pvc-plex-tvshows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-plex-tvshows

