apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  namespace: plex
  name: pvc-plex-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  namespace: plex
  name: pvc-plex-transcode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  namespace: plex
  name: pvc-plex-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-plex-data

