apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  name: pvc-plex-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  name: pvc-plex-movies
spec:
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/movies"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  name: pvc-plex-tvshows
spec:
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/tvshows"


