apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  name: pvc-plex-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-plex-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-tvshows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-plex-tvshows
  

