apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  namespace: plex
  name: svc-plex
spec:
  ports:
    - port: 32400
      protocol: TCP
      targetPort: http-plex
      nodePort: 30327
  selector:
    app: plex      

