---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt
  name: mqtt
  namespace: automation  
spec:
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
              name: mqtt-1883
              protocol: TCP
            - containerPort: 9001
              name: mqtt-9001
              protocol: TCP              
          readinessProbe:
            httpGet:
              port: 9001
              scheme: HTTP          
            # tcpSocket:
            #   port: 1883
            initialDelaySeconds: 10              
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3            
            timeoutSeconds: 2
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10          
            successThreshold: 1
            failureThreshold: 3            
            timeoutSeconds: 2
            httpGet:
              port: 9001
              scheme: HTTP                           
            # tcpSocket:
            #   port: 1883
          volumeMounts:
            - mountPath: /mosquitto/data
              name: mqtt-pv
            - mountPath: /mosquitto/log
              name: mqtt-pv              
      volumes:
        - name: mqtt-pv
          persistentVolumeClaim:
            claimName: mqtt-pvc