# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-nfs-radarr-config
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     server: madara.home
#     path: "/volume1/share/k8s-config/radarr"
#   mountOptions:
#     - nfsvers=4.1
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-radarr-movies
  namespace: radarr  
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: madara.home
    path: "/volume1/share/movies"
  mountOptions:
    - nfsvers=4.1
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-radarr-downloads
  namespace: radarr  
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: madara.home
    path: "/volume1/share/downloads/complete/movies"
  mountOptions:
    - nfsvers=4.1
---       