apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-radarr-config
  namespace: downloads    
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/k8s-config/radarr"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-radarr-movies
  namespace: downloads  
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/movies/"
  mountOptions:
    - nfsvers=4.1
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-radarr-downloads
  namespace: downloads  
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/downloads/"
  mountOptions:
    - nfsvers=4.1
---       