apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: radarr
  name: pvc-radarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
