apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-radarr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-radarr-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-radarr-downloads

