apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: radarr
  name: pvc-radarr-config
  namespace: downloads    
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-radarr-config
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: radarr
#   name: pvc-radarr-config
#   namespace: downloads  
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 400Mi  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: radarr
  name: pvc-radarr-movies
  namespace: downloads  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2000Gi
  volumeName: pv-nfs-radarr-movies

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: radarr
  name: pvc-radarr-downloads
  namespace: downloads  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 150Gi
  volumeName: pv-nfs-radarr-downloads

