apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: emby
  namespace: media
  name: pv-nfs-emby-data
spec:
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: madara.home
    path: "/volume1/share/"
  mountOptions:
    - nfsvers=4.1
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: emby
  namespace: media
  name: pv-nfs-emby-config
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: madara.home
    path: "/volume1/share/k8s-config/emby/"
  mountOptions:
    - nfsvers=4.1
---       
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   labels:
#     app: emby
#   namespace: media
#   name: pv-nfs-emby-media
# spec:
#   capacity:
#     storage: 3000Gi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     server: madara.home
#     path: "/volume1/share/"
#   mountOptions:
#     - nfsvers=4.1