
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: emby
  namespace: media
  name: pvc-emby-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 14Gi
  volumeName: pv-nfs-emby-config      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: emby
  namespace: media
  name: pvc-emby-transcode
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: emby
  namespace: media
  name: pvc-emby-movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-emby-movies
  ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: emby
  namespace: media
  name: pvc-emby-tvshows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: pv-nfs-emby-tvshows

