version: "3.4"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/share/tvshows:/tv
      - /volume1/share/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/share/movies:/movies
      - /volume1/share/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /volume1/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  torrent:
    image: binhex/arch-rtorrentvpn
    container_name: torrent
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=airvpn
      - VPN_CLIENT=openvpn
      - ENABLE_PRIVOXY=yes
      - ENABLE_AUTODL_IRSSI=yes
      - ENABLE_RPC2=yes
      - ENABLE_RPC2_AUTH=no
      - ENABLE_WEBUI_AUTH=no
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - DEBUG=false
      - PHP_TZ=UTC
      - UMASK=000
      - PUID=0
      - PGID=0
    volumes:
        - /volume1/share/downloads:/data
        - /volume1/docker/torrent:/config
        - /etc/localtime:/etc/localtime:ro
    ports:
      - '9080:9080'
      - '9443:9443'
      - '8118:8118'
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /volume1/docker/homeassistant:/config
    ports:
      - 8123:8123
    restart: unless-stopped              
    
