apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: downloads  
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: serier.ting
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-sonarr
            port:
              number: 8989