apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-sonarr-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/k8s-config/sonarr/"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: sonarr
  namespace: downloads  
  name: pv-nfs-sonarr-tvshows 
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/tvshows/"
  mountOptions:
    - nfsvers=4.1
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: sonarr
  namespace: downloads  
  name: pv-nfs-sonarr-downloads
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/volume1/share/downloads/"
  mountOptions:
    - nfsvers=4.1
---       