apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-sonarr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-tvshows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2000Gi
  volumeName: pv-nfs-sonarr-tvshows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 150Gi
  volumeName: pv-nfs-sonarr-downloads

