apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarr
  name: pvc-sonarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
