apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus
  namespace: monitoring
data:
  datasources-prom.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: Server
      url: http://prometheus-server.monitoring.svc.cluster.local
      isDefault: true
      editable: false
      version: 1