apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: prometheus
    datasources:
    - name: prometheus
      type: prometheus
      access: Server
      url: http://prometheus-server.monitoring.svc.cluster.local
      isDefault: true
      editable: false
      version: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alertmanager
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: prometheus
    datasources:
    - name: prometheus
      type: prometheus
      access: Server
      url: http://prometheus-alertmanager.monitoring.svc.cluster.local
      isDefault: true
      editable: false
      version: 1
