apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana 
  namespace: monitoring     
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring    
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana 
        namespace: monitoring
  interval: 5m
  values:
    adminUser: admin
    adminPassword: admin  
    image:
      repository: grafana/grafana
      tag: latest
    service:
      enabled: true
      type: ClusterIP
      port: 80
      targetPort: 3000
      portName: service
    ingress:
      enabled: true
      path: /
      pathType: Prefix
      hosts:
        - grafana.ting  
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true
    dashboards:
      default:
        prometheus-stats:
          gnetId: 2
          revision: 2
          datasource: Prometheus               
          
